name: comunica_tea
description: "COMUNICA-TEA - Plataforma de CAA para TEA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.1.0
  audioplayers: ^6.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  sqflite: ^2.3.0
  path: ^1.9.0
  speech_to_text: ^7.3.0
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logocomunicatea.jpeg
    - assets/sounds/success.mp3
    - assets/sounds/error.mp3
    - assets/images/pictograms/necessidades/
    - assets/images/pictograms/sentimentos/
    - assets/images/pictograms/acoes/
    - assets/images/pictograms/pessoas/
    - assets/images/pictograms/lugares/
    - assets/images/pictograms/objetos/