// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBFbI7gsts_tHIhOR5jviNwnFV7pgDkgI',
    appId: '1:367358880184:web:e171ca5c25614f1575474d', // Nota: Este ID é uma estimativa baseada no Android, o real pode variar levely
    messagingSenderId: '367358880184',
    projectId: 'comunica-tea-ifpe',
    authDomain: 'comunica-tea-ifpe.firebaseapp.com',
    storageBucket: 'comunica-tea-ifpe.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX', // Opcional
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBFbI7gsts_tHIhOR5jviNwnFV7pgDkgI',
    appId: '1:367358880184:android:e171ca5c25614f1575474d',
    messagingSenderId: '367358880184',
    projectId: 'comunica-tea-ifpe',
    storageBucket: 'comunica-tea-ifpe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbPyHP499bs4JFTLyF-DDtrQsMG4Ry3c',
    appId: '1:367358880184:ios:b9a1cfc2a7dc4a2675474d',
    messagingSenderId: '367358880184',
    projectId: 'comunica-tea-ifpe',
    storageBucket: 'comunica-tea-ifpe.firebasestorage.app',
    iosBundleId: 'br.ifpe.palmares.comunicaTea',
  );

}